UFID_LENGTH	= 20

PHASH_SIZE	= 15
DHASH_SIZE	= 15

# Thumbnails
LARGE_THUMB_SIZE		= 500
MEDIUM_THUMB_SIZE		= 250
SMALL_THUMB_SIZE		= 100

LARGE_THUMB_QUALITY		= 95
MEDIUM_THUMB_QUALITY	= 80
SMALL_THUMB_QUALITY		= 20